Post openlab
etalab/entreprise.api.gouv.fr pull request #66
Opened 2020-10-09 11:04 UTC by Haelle

#### Que fait cette PR ?
Ajout de quelques informations dans la doc suite à l'OpenLab

- Changement du logo Infogreffe (il a changé il y a 5 ans...)
- Ajout des horaires de fermetures des APIs de la BdF et DGFiP
- Détail ajouté concernant la MSA

P.S: @DorineLam  @thimy les disponibilité ne s'affichent dans le rendu

2020-10-09 12:15 UTC, skelz0r requested changes
Juste une typo à corriger, sinon c'est OK pour moi.

2020-10-09 12:15 UTC, skelz0r commented on _catalogue/cotisations-de-sécurité-sociale-agricole.md
> +          // Indique "false" quand le statut de l'entreprise est connu, autrement, indique "true" si justement, une analyse manuelle page un agent est en cours.
```suggestion
          // Indique "false" quand le statut de l'entreprise est connu, autrement, indique "true" si justement, une analyse manuelle par un agent est en cours.
```

2020-10-09 12:46 UTC, skelz0r approved these changes

2020-10-12 07:48 UTC, DorineLam approved these changes
Top !

2020-10-12 07:48 UTC, DorineLam commented on _catalogue/cotisations-de-sécurité-sociale-agricole.md
> +        agent de la MSA, ce qui sera indiqué dans la réponse.
Top 👌

2020-10-12 07:48 UTC, DorineLam commented on _catalogue/déclarations-de-résultats.md
> +  unavailability_types: Opérations de maintenance toutes les nuits entre 1h et 2h.
Super ! Pour ces éléments, il faut désormais qu'on les affiche dans l'onglet disponibilité. Je vais ajouter ça dans le backlog. merci

2020-10-12 07:59 UTC, Haelle commented on _catalogue/déclarations-de-résultats.md
> +  unavailability_types: Opérations de maintenance toutes les nuits entre 1h et 2h.
C'est déjà crée !

2020-10-12 07:59 UTC, merged

2020-10-13 10:23 UTC, brindu commented on _catalogue/bilans-annuels-3-dernières-années.md
>      d'erreurs que nous regroupons sous le code HTTP 503 (Service Indisponible)
AMHA on devrait plutôt renvoyer un 502 ici, le code utilisé partout quand l'erreur est située chez le fournisseur de données.

2020-10-14 09:28 UTC, Haelle commented on _catalogue/bilans-annuels-3-dernières-années.md
>      d'erreurs que nous regroupons sous le code HTTP 503 (Service Indisponible)
aujourd'hui on ne renvoie des 502 que quand c'est des 500.

On en a déjà discuté avec @skelz0r et il faudrait revoir toute la base de code pour en effet renvoyer des 502 dans de bien plus nombreux cas. 
FYI @brindu des fois ON se prend des 401 random et on renvoie à nos utilisateurs des 401... donc ça ne concerne même pas que les 50X.
Ça va s'inscrire dans tout le travail que @skelz0r est en train de faire pour mieux gérer les erreurs.